package delivery

import (
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

func GenerateEchoBody(marketAddress common.Address, orderID *big.Int, requestBody []byte) []byte {
	return []byte(fmt.Sprintf(`# Agent Nexus Delivery

## Order

Market: %s
Order ID: %s

## Buyer Request

%s

## Seller Response

This is the first demo delivery generated by the seller service.
`, marketAddress.Hex(), orderID.String(), string(requestBody)))
}
